import 'dart:io';
import 'dart:ui';

import 'package:get/get.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../class/crud.dart';
import '../class/status_request.dart';
import '../constant/id/app_links.dart';
import '../utils/pdf_helpers.dart';
import 'word_export_service.dart';

/// Exports a report as a real Word .docx generated by the backend (PhpWord).
///
/// Unlike the HTML-as-.doc path this produces a genuine OOXML file — Word opens
/// it with no "format & extension don't match" warning. If the backend call
/// fails (offline, endpoint missing…) it transparently falls back to the
/// client-side [WordExportService] so the user still gets a Word file.
class DocxExportService {
  DocxExportService._();

  static Future<void> exportReport({
    required String title,
    required List<String> headers,
    required List<List<String>> rows,
    String? companyName,
    String? subtitle,
    Rect? sharePositionOrigin,
  }) async {
    Get.snackbar(
      'exporting'.tr,
      '',
      snackPosition: SnackPosition.BOTTOM,
      duration: const Duration(seconds: 2),
    );

    try {
      final response = await Get.find<CRUD>().postBytes(
        AppLinks.reportExportWord,
        {
          'title': title,
          if (subtitle != null) 'subtitle': subtitle,
          'company': pdfCompanyTitle(companyName),
          'dir': pdfIsArabic() ? 'rtl' : 'ltr',
          'headers': headers,
          'rows': rows,
        },
      );

      if (response['status'] == StatusRequest.success &&
          response['bytes'] != null) {
        final dir = await getTemporaryDirectory();
        final safeName = title.replaceAll(RegExp(r'\s+'), '_');
        final file = File('${dir.path}/$safeName.docx');
        await file.writeAsBytes(response['bytes'] as List<int>, flush: true);

        await SharePlus.instance.share(
          ShareParams(
            files: [XFile(file.path)],
            title: title,
            sharePositionOrigin: sharePositionOrigin,
          ),
        );

        Get.snackbar(
          'done'.tr,
          'export_success'.tr,
          snackPosition: SnackPosition.BOTTOM,
        );
        return;
      }
    } catch (_) {
      // fall through to the client-side fallback below
    }

    // Backend unavailable — degrade gracefully to the HTML-as-.doc exporter.
    await WordExportService.exportReport(
      title: title,
      headers: headers,
      rows: rows,
      companyName: companyName,
      subtitle: subtitle,
      sharePositionOrigin: sharePositionOrigin,
    );
  }
}
