// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmGiKDCtUEdAuYIZDV7zD5APWrp0wyfsc',
    appId: '1:510933674549:web:9907c72a7e5dc990c35f7c',
    messagingSenderId: '510933674549',
    projectId: 'medjat',
    authDomain: 'medjat.firebaseapp.com',
    storageBucket: 'medjat.firebasestorage.app',
    measurementId: 'G-X5719BMF0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmOmpXWHxt7bkW4wRt7T94Mz1ycXDYNXI',
    appId: '1:510933674549:android:2e6ef02768eb405dc35f7c',
    messagingSenderId: '510933674549',
    projectId: 'medjat',
    storageBucket: 'medjat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArLeUHXjJ2FDNVtG2guBJhaKxpyz2J7S0',
    appId: '1:510933674549:ios:fd425205860b4ad8c35f7c',
    messagingSenderId: '510933674549',
    projectId: 'medjat',
    storageBucket: 'medjat.firebasestorage.app',
    iosClientId: '510933674549-pf3nhmhclogmna7jcrepc5dpfrqarscp.apps.googleusercontent.com',
    iosBundleId: 'com.khawarizmie.medjatCentral',
  );
}
