SET NAMES utf8mb4;

-- ============ 1) SIGNATURE REQUESTS ============
CREATE TABLE IF NOT EXISTS `signature_requests` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL,
  `entity_type` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'document_request (phase 1)',
  `entity_id` int unsigned NOT NULL COMMENT 'document_requests.id',
  `title` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'snapshot of document title at send time',
  `source_pdf_path` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'unsigned PDF path at open time',
  `source_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'sha256 of original file',
  `signed_pdf_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'filled on completion',
  `signed_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'sha256 of final signed PDF',
  `verify_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'unique public verification code',
  `signing_order` enum('sequential','parallel') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'sequential',
  `current_party` tinyint unsigned NOT NULL DEFAULT '1' COMMENT 'current party_order pointer',
  `total_parties` tinyint unsigned NOT NULL,
  `status` enum('pending','completed','declined','voided') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_by` int unsigned DEFAULT NULL COMMENT 'admins.id who sent for signature',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_sig_verify_code` (`verify_code`),
  KEY `idx_sig_tenant_status` (`tenant_id`,`status`),
  KEY `idx_sig_entity` (`tenant_id`,`entity_type`,`entity_id`),
  CONSTRAINT `signature_requests_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `signature_requests_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `admins` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============ 2) SIGNATURE PARTIES ============
CREATE TABLE IF NOT EXISTS `signature_parties` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL,
  `signature_request_id` int unsigned NOT NULL,
  `party_order` tinyint unsigned NOT NULL COMMENT 'starts from 1',
  `signer_type` enum('employee','admin','external') COLLATE utf8mb4_unicode_ci NOT NULL,
  `signer_employee_id` int unsigned DEFAULT NULL,
  `signer_admin_id` int unsigned DEFAULT NULL,
  `signer_name` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'snapshot of name at creation',
  `role_label` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'e.g. Employee / Authorized Manager',
  `status` enum('pending','signed','declined') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `sign_method` enum('drawn','typed','otp') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signature_image_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'when drawn: saved signature image',
  `typed_name` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'when typed',
  `consent_given` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'consented to electronic signature',
  `otp_hash` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'password_hash of sent OTP',
  `otp_expires_at` timestamp NULL DEFAULT NULL,
  `signed_at` timestamp NULL DEFAULT NULL,
  `signed_ip` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signed_user_agent` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `decline_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_party_order` (`signature_request_id`,`party_order`),
  KEY `idx_party_tenant_status` (`tenant_id`,`status`),
  KEY `idx_party_employee` (`signer_employee_id`),
  KEY `idx_party_admin` (`signer_admin_id`),
  CONSTRAINT `signature_parties_ibfk_1` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `signature_parties_ibfk_2` FOREIGN KEY (`signature_request_id`) REFERENCES `signature_requests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `signature_parties_ibfk_3` FOREIGN KEY (`signer_employee_id`) REFERENCES `employees` (`id`) ON DELETE SET NULL,
  CONSTRAINT `signature_parties_ibfk_4` FOREIGN KEY (`signer_admin_id`) REFERENCES `admins` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
