<?php

declare(strict_types=1);

namespace App\Http\Controllers\Employees;

use App\Domain\Audit\AuditLog;
use App\Exceptions\ApiFailure;
use App\Http\ApiResponse;
use App\Models\ActivationCode;
use App\Models\Admin;
use App\Models\Employee;
use App\Models\EmployeeAuthToken;
use App\Support\Value;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * Port of api/app/employees/activation_code.php.
 *
 * Reads the live code and which handset the employee is bound to, and reissues
 * one when the phone changes.
 */
final class ActivationCodeController
{
    public function show(Request $request): JsonResponse
    {
        $tenantId = Value::int($request->attributes->get('tenant_id'));
        $employee = $this->employee($request, $tenantId, Value::int($request->query('id')));

        $code = ActivationCode::query()
            ->usable()
            ->where('employee_id', $employee->id)
            ->orderByDesc('created_at')
            ->first(['code', 'token', 'expires_at']);

        // Scoped to the phone platforms: this block answers which *device* the
        // employee is bound to, and a browser session is not one. Leaving it
        // unscoped would let a web session answer a question the administrator
        // is asking about a handset.
        $device = EmployeeAuthToken::query()
            ->active()
            ->where('employee_id', $employee->id)
            ->whereIn('platform', EmployeeAuthToken::APP_PLATFORMS)
            ->orderByDesc('id')
            ->first(['platform', 'device_model', 'last_used_at']);

        $token = Value::nullableString($code?->token);

        return ApiResponse::success([
            'activation_code' => Value::nullableString($code?->code),
            'activation_token' => $token,
            'join_link' => $token === null ? null : ActivationCode::joinLink($token),
            'expires_at' => Value::nullableString($code?->expires_at),
            'employee_status' => $employee->status,
            'device_bound' => $device !== null,
            'device' => $device === null ? null : [
                'platform' => $device->platform,
                'device_model' => $device->device_model,
                'last_used_at' => $device->last_used_at,
            ],
        ]);
    }

    /**
     * Reissue — which is how a device change is handled.
     *
     * For an already-active employee this is a real security event, not
     * housekeeping: the previous handset loses access immediately and a warning
     * is filed, because "somebody asked for a new code for an account that was
     * working" is exactly the shape of both a lost phone and an attempt to take
     * over an account.
     */
    public function regenerate(Request $request): JsonResponse
    {
        $admin = $request->attributes->get('admin');
        if (! $admin instanceof Admin) {
            throw new ApiFailure('Authentication required', 401);
        }

        $tenantId = Value::int($request->attributes->get('tenant_id'));
        $employee = $this->employee($request, $tenantId, Value::int($request->input('id', $request->query('id'))));

        if ($employee->isTerminated()) {
            throw new ApiFailure(
                'Cannot generate code for terminated employee',
                409,
                'cannot_generate_code_terminated_employee'
            );
        }

        $wasActive = $employee->status === 'active';

        if ($wasActive) {
            EmployeeAuthToken::revokeForEmployee($employee->id, 'admin_regenerated_code');

            DB::table('employees')->where('id', $employee->id)
                ->update(['status' => 'pending_activation']);

            DB::table('warnings')->insert([
                'tenant_id' => $tenantId,
                'employee_id' => $employee->id,
                'type' => 'device_change',
                'reason' => 'Activation code regenerated by admin — previous device token revoked',
                'issued_by' => $admin->id,
            ]);
        }

        $activation = ActivationCode::generateFor($tenantId, $employee->id);

        AuditLog::record(
            $tenantId,
            $admin->id,
            $wasActive ? 'employee.device_reset' : 'employee.regen_code',
            'employee',
            $employee->id,
        );

        return ApiResponse::success([
            'activation_code' => $activation['code'],
            'activation_token' => $activation['token'],
            'join_link' => ActivationCode::joinLink($activation['token']),
            'expires_at' => $activation['expires_at'],
            'activation_expires_in_hours' => ActivationCode::VALIDITY_HOURS,
            'device_revoked' => $wasActive,
        ]);
    }

    private function employee(Request $request, int $tenantId, int $employeeId): Employee
    {
        if ($employeeId <= 0) {
            throw new ApiFailure('Employee ID required', 422, 'employee_id_required');
        }

        $employee = Employee::query()->forTenant($tenantId)->whereKey($employeeId)->first();
        if ($employee === null) {
            throw new ApiFailure('Employee not found', 404);
        }

        return $employee;
    }
}
