<?php

declare(strict_types=1);

namespace App\Http\Controllers\Auth;

use App\Exceptions\ApiFailure;
use App\Http\ApiResponse;
use App\Models\Admin;
use App\Models\DesktopAuthCode;
use App\Services\Auth\FirebaseCustomTokenMinter;
use App\Support\Value;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Desktop sign-in, in two steps.
 *
 * The shell cannot host the sign-in itself — passkeys and the Google flow only
 * work in a real browser — so the person authenticates there and the browser
 * hands a short-lived code back to the app.
 *
 * Ports api/app/auth/desktop_authorize.php and desktop_exchange.php.
 */
final class DesktopAuthController
{
    public function __construct(private readonly FirebaseCustomTokenMinter $minter) {}

    /**
     * Step 1. The caller is already authenticated, so a code is only ever minted
     * for the account signed in right there in the browser.
     */
    public function authorize(Request $request): JsonResponse
    {
        $admin = $request->attributes->get('admin');
        if (! $admin instanceof Admin) {
            throw new ApiFailure('Authentication required', 401);
        }

        $state = Value::string($request->input('state'));

        // Length-checked rather than format-checked: the nonce is generated by
        // the desktop app and only has to be long enough not to be guessed.
        if (strlen($state) < 16 || strlen($state) > 128) {
            throw new ApiFailure('state غير صالح', 400);
        }

        $code = DesktopAuthCode::issue($admin->id, (string) $admin->firebase_uid, $state);

        return ApiResponse::success([
            'code' => $code,
            'expires_in_seconds' => DesktopAuthCode::LIFETIME_SECONDS,
        ]);
    }

    /**
     * Step 2. Deliberately unauthenticated: the code *is* the credential. It is
     * single-use, expires in two minutes, is stored only as a digest, and is
     * bound to the state nonce the desktop app generated.
     */
    public function exchange(Request $request): JsonResponse
    {
        $code = Value::string($request->input('code'));
        $state = Value::string($request->input('state'));

        if ($code === '' || $state === '') {
            throw new ApiFailure('رمز الدخول غير مكتمل', 400);
        }

        $row = DesktopAuthCode::findUsable($code);

        // One message for expired, already used, unknown, and state mismatch.
        // Telling them apart would say which half of the pair was wrong.
        if ($row === null || ! $row->matchesState($state) || ! $row->claim()) {
            throw new ApiFailure(
                'انتهت صلاحية رمز الدخول أو استُخدم بالفعل',
                401,
                'desktop_code_invalid'
            );
        }

        return ApiResponse::success([
            'token' => $this->minter->mint($row->firebase_uid, ['desktop' => true]),
        ]);
    }
}
