<?php
require_once __DIR__ . '/../../config/bootstrap.php';

RateLimiter::enforceIpLimit();
$auth = Auth::authenticateUser(db());
$tenantId = TenantMiddleware::requireTenant();
PermissionMiddleware::check($auth, 'manage_employees');

$employeeId = (int) ($_GET['id'] ?? 0);
if (!$employeeId) {
    Response::fail('Employee ID required', 422);
}

$employee = Database::fetchOne(
    "SELECT id, status FROM employees WHERE id = ? AND tenant_id = ? LIMIT 1",
    [$employeeId, $tenantId]
);
if (!$employee) {
    Response::notFound('Employee');
}

$method = $_SERVER['REQUEST_METHOD'];

if ($method === 'GET') {
    $existing = ActivationCodeModel::findActive($employeeId);
    $activeToken = EmployeeAuthTokenModel::findActiveForEmployee($employeeId);

    Response::success([
        'activation_code' => $existing['code'] ?? null,
        'activation_token' => $existing['token'] ?? null,
        'join_link' => isset($existing['token'])
            ? ActivationCodeModel::buildJoinLink($existing['token'])
            : null,
        'expires_at' => isset($existing['expires_at'])
            ? gmdate('Y-m-d\TH:i:s\Z', strtotime($existing['expires_at']))
            : null,
        'employee_status' => $employee['status'],
        'device_bound' => $activeToken !== null,
        'device' => $activeToken ? [
            'platform' => $activeToken['platform'],
            'device_model' => $activeToken['device_model'],
            'last_used_at' => isset($activeToken['last_used_at'])
                ? gmdate('Y-m-d\TH:i:s\Z', strtotime($activeToken['last_used_at']))
                : null,
        ] : null,
    ]);
}

// POST: regenerate. Allowed for any non-terminated employee — covers device change (PRD §3.6).
if (in_array($employee['status'], ['terminated'], true)) {
    Response::fail('Cannot generate code for terminated employee', 409);
}

$wasActive = $employee['status'] === 'active';

if ($wasActive) {
    EmployeeAuthTokenModel::revokeForEmployee(
        $employeeId,
        'admin_regenerated_code'
    );
    Database::execute(
        "UPDATE employees SET status = 'pending_activation' WHERE id = ?",
        [$employeeId]
    );
    WarningModel::add(
        $employeeId,
        $tenantId,
        'device_change',
        'Activation code regenerated by admin — previous device token revoked',
        $auth['admin_id']
    );
}

$activation = ActivationCodeModel::generate($tenantId, $employeeId);
$expiresAt = gmdate('Y-m-d\TH:i:s\Z', strtotime('+24 hours'));

AuditLogModel::log(
    $tenantId,
    $auth['admin_id'],
    $wasActive ? 'employee.device_reset' : 'employee.regen_code',
    'employee',
    $employeeId
);

Response::success([
    'activation_code' => $activation['code'],
    'activation_token' => $activation['token'],
    'join_link' => ActivationCodeModel::buildJoinLink($activation['token']),
    'expires_at' => $expiresAt,
    'activation_expires_in_hours' => 24,
    'device_revoked' => $wasActive,
]);
