include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    curly_braces_in_flow_control_structures: warning
    library_private_types_in_public_api: error
    missing_required_param: error
    missing_return: error
    invalid_override: error

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/build/**"
    - "**/coverage/**"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true

    avoid_print: true
    avoid_empty_else: true
    avoid_unused_constructor_parameters: true
    prefer_final_locals: true
    prefer_final_fields: true
    unnecessary_nullable_for_final_variable_declarations: true

    unawaited_futures: true
    avoid_void_async: true
    await_only_futures: true

    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_if_null_operators: true
    avoid_redundant_argument_values: true
    avoid_multiple_declarations_per_line: true
    prefer_single_quotes: true

    prefer_typing_uninitialized_variables: true
    unnecessary_overrides: true
    unnecessary_getters_setters: true
    unnecessary_parenthesis: true
    use_build_context_synchronously: true
    prefer_interpolation_to_compose_strings: true

    no_logic_in_create_state: true
    prefer_const_declarations: true
